### ISSUE TITLE
How to add inline keyboard?

### ISSUE THREAD

**Issue by tsurkys** [Arkoniak/Telegram.jl#14]
Could you please give an example of sending a message with  InlineKeyboardButton...

**Comment by tsurkys** [comment]
Could you please give an example of sending a message with InlineKeyboardButton

**Comment by Arkoniak** [comment]
It should be similar to the usual `ReplyKeyboard`, but instead of `keyboard` you should use `inline_keyboard` keyword. You may find an example of the regular keyboard in https://arkoniak.github.io/Telegram.jl/stable/usage/#Turtle-graphics-bot

I havn't tried it myself, but it should be something like
```
sendMessage(text = "Test inline keyboard", reply_markup = Dict(:inline_keyboard => [[Dict(:text => "test", :url => "https://example.com")]]), chat_id = chat_id)
```

**Comment by tsurkys** [comment]
Thank you. Now it is clear.
